---
ID: "cfcd1cb0-ce8b-5739-ae9c-b1a36d2c3508"
Parent: "c9a725a1-fb07-581b-abf3-3db8b428af19"
Template: "c9a725a1-fb07-581b-abf3-3db8b428af19"
Path: "/sitecore/templates/Project/headlessapp/GraphQL-IntegratedDemo/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230424T033339Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3a6e31bc-e21d-40fb-a56b-86c67c1b4321"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230424T033339Z
